proxy:
  port: 9090

routes:
  - host: "app.example.com"
    destination: "localhost"
    port: 3000
    path: "/"
    tls: false

  - host: "app.example.com"
    destination: "localhost"
    port: 4000
    path: "/test"
    tls: false

  - host: "api.example.com"
    destination: "localhost"
    port: 5000
    path: "/"
    tls: false