proxy:
  http:
    enabled: true
    port: 8880
    redirect_to_https: true

  https:
    enabled: true
    port: 8443
    cert: "cert.pem"
    key: "key.pem"

routes:
  - host: "app.example.com"
    destination: "localhost"
    port: 3000
    path: "/"
    tls: false

  - host: "app.example.com"
    destination: "localhost"
    port: 4000
    path: "/test/{rest...}"
    tls: false

  - host: "api.example.com"
    destination: "localhost"
    port: 5000
    path: "/"
    tls: false